#!/bin/sh
set -euo pipefail
# Initialization - load function handler
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"
# State file
STATE=$(mktemp)
echo "STATE-FILE: $STATE" >>$STATE
echo "AWS_LAMBDA_RUNTIME_API: $AWS_LAMBDA_RUNTIME_API" >>$STATE
# Processing
while true; do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  echo "HEADERS: $(cat $HEADERS)" >>$STATE
  echo "EVENT_DATA: $EVENT_DATA" >>$STATE
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)
  echo "REQUEST_ID: $REQUEST_ID" >>$STATE
  # Execute the handler function from the script
  RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")
  echo "RESPONSE: $RESPONSE" >>$STATE
  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" --data-binary "@$STATE"
done
