#!/bin/sh
set -euo pipefail
# State file
STATE=$(mktemp)
echo "STATE-FILE: $STATE" >>$STATE
echo "_HANDLER: $_HANDLER" >>$STATE
echo "LAMBDA_TASK_ROOT: $LAMBDA_TASK_ROOT" >>$STATE
echo "AWS_LAMBDA_RUNTIME_API: $AWS_LAMBDA_RUNTIME_API" >>$STATE
# Processing
while true; do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  echo "HEADERS: $(cat $HEADERS)" >>$STATE
  echo "EVENT_DATA: $EVENT_DATA" >>$STATE
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)
  echo "REQUEST_ID: $REQUEST_ID" >>$STATE
  echo "ENV_VARS: $(env)" >>$STATE
  # Execute the handler function from the script
  RESPONSE="{{$EVENT_DATA}}"
  echo "RESPONSE: $RESPONSE" >>$STATE
  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" --data-binary "@$STATE"
done
